title: Frenny Macwan # your name (or website title) here
logo: "/fm.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Data Scientist
  <br><br>
  <a href="mailto:freny.mcwan@gmail.com">freny.mcwan@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/frenny-macwan">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/FrennyMacwan/">Gihub</a> 
theme: jekyll-theme-minimal
